<div class="col-md-12">
    <?php $elements->getTabsActeur(); ?>
    <?php echo $this->getContent();
    ?>
    <div class="page-header">
        <h1>
            Liste de tout mes projets
        </h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <table class="table table-bordered">
                <tbody>
                <ul class="list-group">
                    <?php foreach ($page->items as $projet): ?>
                    <li class="list-group-item list-group-item-warning text-center" onclick="Projet.affiche(<?php echo $projet->id?>);"><?php echo $projet->libelle ?><br>
                    <li class="list-group-item"  id="<?php echo $projet->id?>" style="display: none">
                    <?php endforeach; ?>
                </ul>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("projet/indexActeur", "Première page") ?></li>
                <li><?php echo $this->tag->linkTo("projet/indexActeur?page=" . $page->before, "Précedente") ?></li>
                <li><?php echo $this->tag->linkTo("projet/indexActeur?page=" . $page->next, "Suivante") ?></li>
                <li><?php echo $this->tag->linkTo("projet/indexActeur?page=" . $page->last, "Dernière page") ?></li>
            </ul>
        </nav>
    </div>
</div>

<script type="text/javascript" src="/gestEventv2/js/leProjetActeur.js"></script>
