<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="col-md-12">
    <?php $elements->getTabsAdmin(); ?>
    <div class="row">
        <div class="col-sm-1">
            <nav>
                <ul class="pager">
                    <li class="previous"><?php echo $this->tag->linkTo(["acteur", "Accueil"]) ?></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="page-header">
        <h1>
            Modification de l'acteur
        </h1>
    </div>

    <?php echo $this->getContent(); ?>

    <?php
        echo $this->tag->form(
            [
                "acteur/save",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            ]
        );
    ?>

    <div class="form-group">
        <label for="fieldNom" class="col-sm-1 control-label">Nom</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["nom", "size" => 30, "class" => "form-control", "id" => "fieldNom"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldPrenom" class="col-sm-1 control-label">Prenom</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["prenom", "size" => 30, "class" => "form-control", "id" => "fieldPrenom"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldLogin" class="col-sm-1 control-label">Login</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["login", "size" => 30, "class" => "form-control", "id" => "fieldLogin"]) ?>
        </div>
    </div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <?php echo $this->tag->submitButton(["Sauvegarder", "class" => "btn btn-default"]) ?>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>
</div>