<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="col-md-12">
    <?php $elements->getTabsAdmin(); ?>
    <div class="row col-md-12">
    <?php use Phalcon\Tag; ?>
        <nav>
            <ul class="pager col-md-12" >
                <li class="previous"><?php echo $this->tag->linkTo(["acteur/index", "Accueil"]); ?></li>
                <li class="next"><?php echo $this->tag->linkTo(["acteur/new", "Créer "]); ?></li>
            </ul>
        </nav>

        <div class="page-header">
            <h1>Résultat de la recherche</h1>
            <?php echo $this->getContent(); ?>
        </div>

        <div class="row col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prenom</th>
                        <th>Catégorie</th>
                        <th>Login</th>

                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($page->items as $acteur): ?>
                    <tr>
                        <td><?php echo $acteur->nom ?></td>
                        <td><?php echo $acteur->prenom ?></td>
                        <td><?php echo $acteur->categorie ?></td>
                        <td><?php echo $acteur->login ?></td>
                        <td><?php echo $this->tag->linkTo(["acteur/edit/" . $acteur->id, "Modification"]); ?></td>
                        <td><?php echo $this->tag->linkTo(["acteur/delete/" . $acteur->id, "Suppression"]); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-sm-1">
                <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                    <?php echo $page->current, "/", $page->total_pages ?>
                </p>
            </div>
            <div class="col-sm-11">
                <nav>
                    <ul class="pagination">
                        <li><?php echo $this->tag->linkTo("acteur/search", "Première page") ?></li>
                        <li><?php echo $this->tag->linkTo("acteur/search?page=" . $page->before, "Précédente") ?></li>
                        <li><?php echo $this->tag->linkTo("acteur/search?page=" . $page->next, "Suivante") ?></li>
                        <li><?php echo $this->tag->linkTo("acteur/search?page=" . $page->last, "Dernière page") ?></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>