<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="col-md-12">
<?php $elements->getTabsAdmin(); ?>
    <div class="row col-md-12">
        <nav>
            <ul class="pager">
                <li class="previous"><?php echo $this->tag->linkTo(["tache/indexAdmin", "Accueil"]) ?></li>
            </ul>
        </nav>
    </div>

    <div class="page-header">
        <h1>
            Modifier une tâche
        </h1>
    </div>

    <?php echo $this->getContent(); ?>

    <?php
        echo $this->tag->form(
            [
                "tache/saveAdmin",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            ]
        );
    ?>

    <div class="form-group">
        <label for="fieldLibelle" class="col-sm-2 control-label">Libelle</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["libelle", "size" => 30, "class" => "form-control", "id" => "fieldLibelle"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldDuree" class="col-sm-2 control-label">Durée</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["duree", "type" => "number", "class" => "form-control", "id" => "fieldDuree"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldDateDebut" class="col-sm-2 control-label">Date début</label>
        <div class="col-sm-10">
            <?php echo $this->tag->dateField(["dateDebut", "size" => 30, "class" => "form-control", "id" => "fieldDateDebut"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldDateFin" class="col-sm-2 control-label">Date fin</label>
        <div class="col-sm-10">
            <?php echo $this->tag->dateField(["dateFin", "size" => 30, "class" => "form-control", "id" => "fieldDateFin"]) ?>
        </div>
    </div>

    <div class="form-group ">
        <label for="fieldEtats" class="col-sm-2 control-label ">Etat</label>
        <div class="col-sm-10 pull-right ">
                <?php
                echo $this->tag->selectStatic(
                    [
                        "class" => "form-control",
                        "etat",
                        [
                            "En cours" => "En cours",
                            "Terminée"   => "Terminée",
                            "Non débutée"    => "Non débutée",
                        ]
                    ]
                );?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldCommentaire" class="col-sm-2 control-label">Commentaire</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["commentaire", "size" => 30, "class" => "form-control", "id" => "fieldCommentaire"]) ?>
        </div>
    </div>


    <?php echo $this->tag->hiddenField("id") ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Sauvegarder", "class" => "btn btn-default"]) ?>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>
</div>